travis:
  secure:
    BINSTAR_TOKEN: hFJhrK/xgwIGkFxL5ikuDy43nb2U/jRK9V0JKqcLw9nxc9HW6PDA7iF3wiI2FH904M4Efu24WAM4WzuKmXnpeOXXKo5J4HKdvZo0u6sFX6BYtbuWgdg4+G14OtW+PDwmg0c7r04QaLnfbRqdCONlHWLtfskGwl+tOMb3srBO/ftXPzgB9aJCQ/SI7seh356B68ytp3F3RJDYZ8cXiP69BFYWpUlqxpsMRtlBoZn93JtbOs8LvWNbSXVgv7gM6qlIfCQhorwTGAfrK14ge2cRoaB0qwKqUJQ5/TSVu5kP7WvYgAp8BVhwSBhXwwq/dcICr4rgkpwZcW5HT4oUknlalwY+q0Y8UyHi4IPYRa+RSNXCCHKk4GBAK7TiQfUQ8cRSD/IEjHOKstVGUXHrq3QsSiJb6sDAtY5ONaxsYDYY86vFWbpm8A8J/cxoVYsNnWp2jBnDrlru1p/IHn9zXN+kTD3+aNLAl7QaPcwInoUfwhbJfn2dm1kY10a2jqi7JjNKp1fTPsAA1qbyLVibGhXjH+WvYqkv9GfPR7V66v4DsEE00WjGDPriAkmhPJb6PmLeCTUELUPZwIQTsKECkO29MnBoQ6+Fit7pSPUTtMpMYqJTnozplt4Uv0tuT1YDhht9EeNym2foHAfe/+VhRB33vWALoSyeg57yKRzGmvenkp4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
